version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8008:8000"
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEVICE=cpu
    volumes:
      - ./models:/app/models
      - ./docs:/app/docs

  db:
    image: 'postgres:13'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - './db-data:/var/lib/postgresql/data'
    ports:
      - '5435:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080